### PR TITLE
Removing Buchi from CODEOWNERS

### PR DESCRIPTION
**Pull request by buchi-busireddy**
## Description
Removing Buchi from CODEOWNERS

### Testing
Node code changes, just GH config changes so no testing done.

### Checklist:
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by jcchavezs — APPROVED** [review]

**Comment by aaron-steinfeld** [comment]
Hah, the tests will miss you! But really, shows an issue we have with forked PRs - we should fix and skip if pushing UT results back to the PR fails: Example: https://github.com/hypertrace/hyperdash/blob/main/.github/workflows/build-and-test.yml#L58
Will tack it on to this PR real quick.

**Comment by aaron-steinfeld** [comment]
> Hah, the tests will miss you! But really, shows an issue we have with forked PRs - we should fix and skip if pushing UT results back to the PR fails: Example: https://github.com/hypertrace/hyperdash/blob/main/.github/workflows/build-and-test.yml#L58
> Will tack it on to this PR real quick.

Nevermind, it's from buchi's fork. Let me raise a separate PR

**Comment by aaron-steinfeld** [comment]
https://github.com/hypertrace/data-model/pull/21

**Comment by JBAhire** [comment]
> Hah, the tests will miss you! But really, shows an issue we have with forked PRs - we should fix and skip if pushing UT results back to the PR fails: Example: https://github.com/hypertrace/hyperdash/blob/main/.github/workflows/build-and-test.yml#L58
> Will tack it on to this PR real quick.

Yeah, we handled this in other repos where most of the work happens and people will raise PRs from forks but left others as it is.

**Review by JBAhire — APPROVED** [review]

**Pull request merged**
